baseurl: /istanbul
permalink: pretty
future: true
markdown: kramdown
paginate: 5
repo: istanbul
github_org: maptime
maptime:
  chapter: MaptimeIstanbul
  #twitter: TwitterHandle
  #disqus: YOUR DISQUS USERNAME

gems:
  - jekyll-feed
